// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
namespace MyMLApp
{
    public partial class Mlmodelim
    {
        /// <summary>
        /// model input class for Mlmodelim.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Görüş")]
            public string Görüş { get; set; }

            [ColumnName(@"Durum")]
            public string Durum { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Mlmodelim.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Görüş")]
            public float[] Görüş { get; set; }

            [ColumnName(@"Durum")]
            public uint Durum { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("mlmodelim.zip");

        // PredictionEngine'in değerini tutmak için Lazy kullanılır
        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// ModelInput üzerinde tahmin yapmak için bu yöntemi kullanın.
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        // <param name="input">model girdisi.</param>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            // ML.NET Model Builder tarafından oluşturulan model yüklenir
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            // PredictionEngine oluşturulur

            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
